packages:
  - name: wayland
    version: 1.22.0-2.1
    url: http://deb.debian.org/debian/pool/main/w/wayland/wayland_1.22.0-2.1.dsc
    build_type: standard
  - name: wayland-protocols
    version: 1.36
    url: http://deb.debian.org/debian/pool/main/w/wayland-protocols/wayland-protocols_1.36-1.dsc
    build_type: standard
  - name: dpkg
    version: 1.22.10
    url: http://deb.debian.org/debian/pool/main/d/dpkg/dpkg_1.22.10.dsc
    build_type: standard
  - name: libliftoff
    version: 0.4.1
    url: https://salsa.debian.org/debian/libliftoff/-/archive/debian/latest/libliftoff-debian-latest.tar.gz
    build_type: custom
  - name: libdisplay-info
    version: 0.1.1-2
    url:  http://deb.debian.org/debian/pool/main/libd/libdisplay-info/libdisplay-info_0.1.1-2.dsc
    build_type: standard
  - name: wlroots
    version: 0.17.4-1
    url: http://deb.debian.org/debian/pool/main/w/wlroots/wlroots_0.17.4-1.dsc 
    build_type: standard
  - name: labwc
    version: 0.7.3
    url: https://github.com/labwc/labwc/archive/refs/tags/0.7.3.tar.gz
    build_type: custom  
    package_config_dir: debian