name: Bootloader Build
on:
  push:
    branches:
      - main
      - dev*
    paths:
      - bootloader/**  
      - .github/workflows/bootloader-build.yml

jobs:
  build:
    runs-on: ubicloud-standard-2-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install basic dependencies
        run: |
           sudo apt-get update
           sudo apt-get install -y curl wget

      - name: Install Nushell
        run: |
          ARCH=$(uname -m) && \
          case ${ARCH} in \
          x86_64) NUSHELL_ARCH="x86_64-unknown-linux-gnu" ;; \
          aarch64) NUSHELL_ARCH="aarch64-unknown-linux-gnu" ;; \
          armv7l) NUSHELL_ARCH="armv7-unknown-linux-gnueabihf" ;; \
          *) echo "Unsupported architecture: ${ARCH}" && exit 1 ;; \
          esac && \
          wget https://github.com/nushell/nushell/releases/download/0.96.0/nu-0.96.0-${NUSHELL_ARCH}.tar.gz && \
          tar -xzvf nu-0.96.0-${NUSHELL_ARCH}.tar.gz && \
          sudo mv nu-0.96.0-${NUSHELL_ARCH}/nu /usr/local/bin/ && \
          rm -rf nu-0.96.0-${NUSHELL_ARCH}.tar.gz nu-0.96.0-${NUSHELL_ARCH}

      - name: Read and Install Additional Dependencies
        run: |
          PACKAGES=$(nu -c "open bootloader/conf-packages/host.yml | get packages | str join ' '")
          sudo apt-get install -y $PACKAGES   


      - name: Build Directory
        run: |
          mkdir -p build

      - name: Run Bootloader Build Script
        run: |
          cd bootloader
          nu build-bootloader.nu mecha-comet-gen1 ../build

      - name: List all files
        run: |
          ls -laR build/deploy

      - name: Prepare bootloader artifacts
        run: |
            mkdir artifacts
            VERSION=$(nu -c "open bootloader/machines/mecha-comet-gen1.yml | get version")
            for file in build/deploy/u-boot/*; do
              base=$(basename "$file")
              mv "$file" "artifacts/${base%.bin}-v${VERSION}.bin"
            done

      - name: List all Artifacts
        run: |
          ls -laR artifacts  

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bootloader-artifacts
          path: ./artifacts/*

