name: debian build
on:
  push:
    branches:
      - main
      - dev*

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update -y && \
          apt-get install -y \
          wget \
          build-essential \
          dpkg-dev \
          debhelper \
          devscripts \
          git \

      - name: Create assets directory
        run: | 
            mkdir -p assets


      - name: Build debian for bluetooth
        run: |
             cd firmware/bluez/bluez-1.0
             dpkg-buildpackage -us -uc
             cp ../*.deb  $GITHUB_WORKSPACE/assets/
             ls -la ../

      - name: Build debian for Imx-sdma
        run: |
          cd firmware/imx-sdma-firmware/imx-sdma-firmware-1.0
          dpkg-buildpackage -us -uc
          cp ../*.deb $GITHUB_WORKSPACE/assets/
          ls -la ../

      - name: list all contents of assets
        run: |
           ls -la $GITHUB_WORKSPACE/assets/
