name: Build easysplash

on:
  push:
    branches:
      - main
      - dev*
    paths:
    - debian/**
    - .github/workflows/package-build.yml


jobs:
  build:
    runs-on: ubuntu-22.04

    env:
      DEBEMAIL: "dhruveshb@mechasystems.com"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Debug - List contents of debian directory
        run: |
          ls -R debian/packages/easy-splash/easy-splash-swrender/debian

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./debian/packages/easy-splash/easy-splash-swrender/Dockerfile
          platforms: linux/arm64
          push: false
          load: true
          tags: mechasystems/easy-splash-swrender:latest

      - name: Debug - List Docker images
        run: docker images

      - name: Debug - Show Docker image details
        run: docker inspect mechasystems/easy-splash-swrender:latest

      - name: Remove existing container if it exists
        run: |
          docker rm -f easysplash-container || true

      - name: Run Docker container and collect artifacts
        run: |
          docker run  --platform linux/arm64 --name easysplash-container mechasystems/easy-splash-swrender:latest
          docker ps -a
          docker logs easysplash-container
          docker cp easysplash-container:/artifacts ./artifacts || echo "Failed to copy artifacts"

      - name: Debug - List container filesystem
        if: failure()
        run: |
          docker exec easysplash-container ls -R /

      - name: list artifacts
        run: |
          ls -R ./artifacts || echo "No artifacts found"

      - name: Clean up
        if: always()
        run: |
          docker stop easysplash-container || true
          docker rm easysplash-container || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: easysplash-swrender-artifacts
          path: ./artifacts/*    
